server:
  port: 9000

#服务名
spring:
  application:
    name: api-gateway

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#自定义路由映射
zuul:
  routes:
    #路由映射(例如http://localhost:9000/product-service/api/v1/product/find?id=2映射为http://localhost:9000/apigateway/order/api/v1/product/find?id=2)
    order-service: apigateway/order/**
    product-service: apigateway/product/**
#忽略整个服务对外提供接口(就是不能通过http://localhost:9000/product-service/api/v1/product/find?id=2这样的方式访问服务)
  #ignored-services: product-service
  #忽略所有以service结尾的服务，对外提供接口
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题（通过网关路由转发，cookie会被过滤，所以该设置将添加过滤请求头的列表清空）
  sensitive-headers:
